# Generated by Django 5.1.7 on 2025-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_asset', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='website',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
