# Generated by Django 5.1.7 on 2025-03-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_asset', '0002_delete_asset_remove_manufacturer_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
