# Generated by Django 5.1.7 on 2025-03-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_asset', '0003_remove_employee_department_remove_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
