# Generated by Django 5.1.7 on 2025-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_asset', '0004_remove_profile_address_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
