# Generated by Django 5.1.7 on 2025-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_asset', '0006_employee_department_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
